import { cn } from "@/lib/utils";
import "./globals.css";
import { DM_Sans as FontSans } from "next/font/google"


const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(
        "min-h-screen bg-[#F5F5F5] font-sans antialiased container pt-5",
        fontSans.variable
      )}>{children}</body>
    </html>
  );
}
